// src/components/HeaderPage.vue
<template>
  <header>
   <div class="header-bottom">
    <div class="container">
      <div class="row">
        <div class="col-sm-9">
          <div class="mainmenu pull-left">
            <ul class="nav navbar-nav collapse navbar-collapse">
              <li><router-link :to="{name:'Home'}" >Accueil</router-link></li>
              <li class="dropdown"><router-link :to="{name:'Cart'}" >Mon panier</i></router-link>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="search_box pull-right">
            <input type="text" v-if="this.$route.name == 'Home'" id="SerachInput" v-model="search" placeholder="Search"/>
          </div>
        </div>
      </div>
    </div>
  </div>
  </header>
</template>

<script>
  import ListBooks from '../store/ListBooks'

  export default {
    name: 'HeaderPage',
    data () {
      return {
        search: '',
        state: ListBooks.state
      }
    },
    watch: {
      search: function () {
        this.state.searchInput = this.search
      }
    }
  }
</script>

// src/app/header-page/header-page.component.ts
import { Component, OnInit } from '@angular/core';
import {BookService} from '../common/books.service';

@Component({
  selector: 'app-header-page',
  templateUrl: './header-page.component.html'
})
export class HeaderPageComponent implements OnInit {
  search: string = "";
  constructor(private bookService:BookService) { }

  ngOnInit() {
    this.bookService.setSearchInput(this.search);
  }
  triggerChange(){
    this.bookService.setSearchInput(this.search);
  }
}

<header>
  <div class="header-bottom">
    <div class="container">
      <div class="row">
        <div class="col-sm-9">
          <div class="mainmenu pull-left">
            <ul class="nav navbar-nav collapse navbar-collapse">
              <li><a [routerLink]="['/home']">Accueil</a></li>
              <li class="dropdown"><a [routerLink]="['/panier']">Mon panier</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="search_box pull-right">
            <input type="text"  id="SerachInput" [(ngModel)]="search" (ngModelChange)="triggerChange()" placeholder="Search"/>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
