// src/app/footer-page/footer-page.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-footer-page',
  templateUrl: './footer-page.component.html'
})
export class FooterPageComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<footer v-once id="footer">
  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <p class="pull-left">Copyright © 2017 Application. All rights reserved.</p>
        <p class="pull-right">Developed by <span>Abdellah</span></p>
      </div>
    </div>
  </div>
</footer>

// src/components/FooterPage.vue
<template>
   <footer v-once id="footer">
    <div class="footer-bottom">
      <div class="container">
        <div class="row">
          <p class="pull-left">Copyright © 2017 Application. All rights reserved.</p>
          <p class="pull-right">Developed by <span>Abdellah</span></p>
        </div>
      </div>
    </div>
  </footer>
</template>

<script>
  export default {
    name: 'FooterPage'
  }
</script>
