// src/components/Home.vue
<template>
  <section>
    <div class="container">
      <div class="row">
        <div class="features_items">
          <h2 class="title text-center">Les derniers livres</h2>
          <div v-for="book in searchedBooks" class="col-sm-4">
            <Book page="home" :book="book"></Book>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>

  import Book from '@/components/Book'
  import ListBooks from '../store/ListBooks'
  import _ from 'lodash'

  export default {
    name: 'Home',
    components: {Book},
    data () {
      return {
        state: ListBooks.state
      }
    },
    computed: {
      searchedBooks: function () {
        return this.state.books.filter((book) => {
          return this.checkIfSearchInputexistInAttributsOfBook(book)
        })
      }
    },
    methods: {
      ckeckIfStringContainsSearchInput: function (value) {
        return value.toUpperCase().includes(this.state.searchInput.toUpperCase())
      },
      checkIfSearchInputexistInAttributsOfBook: function (object) {
        return _.some(_.values(object), attribut => {
          if (typeof attribut === 'object') {
            return this.checkIfSearchInputexistInAttributsOfBook(attribut)
          } else if (typeof attribut === 'string') {
            return this.ckeckIfStringContainsSearchInput(attribut)
          }
        })
      }
    },

    mounted () {
      if (this.state.books.length > 0) return
      this.$http.get('api/books').then(response => {
        ListBooks.fillListBooks(response.body)
      })
    }
  }
</script>

// src/app/home/home.component.ts
import {Component, OnInit} from '@angular/core';
import {HomeService} from './home.service';
import {Book} from '../common/book.model';
import {BookService} from '../common/books.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  providers: [HomeService]
})
export class HomeComponent implements OnInit {
  books:Book[] = [];

  constructor(private homeService:HomeService, private bookService:BookService) {
  }

  ngOnInit() {
    this.homeService.getBooks().subscribe(books => {
      this.books = books;
    });
  }

  getSearchedBooks(){
    return this.books.filter((book) => {
      return this.checkIfSearchInputexistInAttributsOfBook(book);
    })
  }

  checkIfSearchInputexistInAttributsOfBook(object){
    return Object.values(object).some( attribut => {
      if (typeof attribut === 'object') {
        return this.checkIfSearchInputexistInAttributsOfBook(attribut)
      } else if (typeof attribut === 'string') {
        return this.ckeckIfStringContainsSearchInput(attribut)
      }
    })
  }

  ckeckIfStringContainsSearchInput(value){
    return value.toUpperCase().includes(this.bookService.getSearchInput().toUpperCase())
  }


}

<section>
  <div class="container">
    <div class="row">
      <div class="features_items">
        <h2 class="title text-center">Les derniers livres</h2>
        <div *ngFor="let book of getSearchedBooks()" class="col-sm-4">
         <app-book [book]="book"></app-book>
        </div>
      </div>
    </div>
  </div>
</section>
